apiVersion: v1
kind: Pod
metadata:
  name: multi-pod 
  labels:
    app: multi-pod
spec:
  containers:
    - name: alpha
      image: nginx:1.23.1-alpine
      env: 
      - name: alpha
        value: beta
    - name: : beta
      image: busybox:latest
      args:
      - sleep
      - "4800" 
      env: 
      - name: beta
        value: beta
